version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    reviewers:
      - "devops-team"
    assignees:
      - "lead-developer"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    
    # Group related updates
    groups:
      react:
        patterns:
          - "react"
          - "react-*"
          - "@types/react*"
      testing:
        patterns:
          - "*jest*"
          - "@testing-library/*"
          - "cypress"
          - "playwright"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      next:
        patterns:
          - "next"
          - "@next/*"
    
    # Allow specific updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
        update-type: "security"
    
    # Ignore specific packages (if needed)
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "devops-team"
    labels:
      - "github-actions"
      - "ci-cd"
      - "automated"
    open-pull-requests-limit: 3

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "docker"
      include: "scope"
    reviewers:
      - "devops-team"
    labels:
      - "docker"
      - "infrastructure"
      - "automated"