# Render.com Blueprint Configuration
# Deploys judge.ca platform with PostgreSQL database

services:
  # Main Application (Express.js + Next.js)
  - type: web
    name: judge-ca
    env: node
    region: oregon
    plan: starter
    branch: master
    buildCommand: npm install && npm run build && npm run build:backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: judge-ca-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: REDIS_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: https://judge-ca.onrender.com
      - key: NEXT_PUBLIC_WEBSOCKET_URL
        value: wss://judge-ca.onrender.com
      - key: CORS_ORIGIN
        value: https://judge-ca.onrender.com
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TWILIO_VERIFY_SERVICE_SID
        sync: false
      - key: SENTRY_DSN
        sync: false

databases:
  # PostgreSQL Database
  - name: judge-ca-db
    plan: starter
    databaseName: judge_ca_production
    user: judge_ca_user
    region: oregon

# Health check configuration
healthCheckPath: /api/health
